"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["a.goBack[_ngcontent-%COMP%] {\r\n  text-decoration: underline;\r\n}\r\n\r\n.auth[_ngcontent-%COMP%] {\r\n  color: green;\r\n  font-size: 36px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=dashboard.component.css.shim.ngstyle.js.map