"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["header[_ngcontent-%COMP%] {\r\n  text-align: center;\r\n  padding: 20px 0;\r\n  font-size: 50px;\r\n  border-bottom: 2px solid #eee;\r\n  background: #666;\r\n  color: white;\r\n}\r\n\r\n.subtitle[_ngcontent-%COMP%] {\r\n  font-size: 18px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=header.component.css.shim.ngstyle.js.map