"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".menuTop[_ngcontent-%COMP%] {\r\n  padding: 5px;\r\n  background: #e6e6e6;\r\n}\r\n\r\n.hintText[_ngcontent-%COMP%] {\r\n  margin: 15px;\r\n  font-style: italic;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=home.component.css.shim.ngstyle.js.map