"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["[_nghost-%COMP%] {\r\n  flex-grow: 1;\r\n  display: flex;\r\n  justify-content: center;\r\n  align-items: center;\r\n}\r\n\r\ndiv.input[_ngcontent-%COMP%] {\r\n  position: relative;\r\n}\r\n\r\ndiv.input[_ngcontent-%COMP%]   label[_ngcontent-%COMP%] {\r\n  position: absolute;\r\n  top: 0;\r\n  transform: translateY(-50%);\r\n  left: 10px;\r\n  background: white;\r\n  padding: 5px 2px;\r\n}\r\n\r\ndiv.input[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\r\n  padding: 10px 20px;\r\n  font-size: 25px;\r\n  outline: 0;\r\n}\r\n\r\ndiv.input[_ngcontent-%COMP%] {\r\n  margin-top: 20px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=login-form.component.css.shim.ngstyle.js.map